# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])

# Brand Seeds
Brand.find_or_create_by(name: "Sony")
Brand.find_or_create_by(name: "Warhammer 40,000")
Brand.find_or_create_by(name: "Ubisoft")
Brand.find_or_create_by(name: "Sanyo")
Brand.find_or_create_by(name: "Atari")
Brand.find_or_create_by(name: "VALORANT")
Brand.find_or_create_by(name: "Electronic Arts")
Brand.find_or_create_by(name: "Zoom (company)")
Brand.find_or_create_by(name: "Animoca Brands")
Brand.find_or_create_by(name: "The Sims (video game)")
Brand.find_or_create_by(name: "DMarket")
Brand.find_or_create_by(name: "Improbable (company)")
Brand.find_or_create_by(name: "Nintendo")
Brand.find_or_create_by(name: "MechaFightClub")
Brand.find_or_create_by(name: "Krafton")
Brand.find_or_create_by(name: "Tencent")
Brand.find_or_create_by(name: "Rockstar Games")
Brand.find_or_create_by(name: "Zynga")
Brand.find_or_create_by(name: "Epic Games")
Brand.find_or_create_by(name: "Activision")
Brand.find_or_create_by(name: "GameStop")
Brand.find_or_create_by(name: "Bethesda Softworks")
Brand.find_or_create_by(name: "Lucasfilm")
Brand.find_or_create_by(name: "Croteam")
Brand.find_or_create_by(name: "Conan Exiles")
Brand.find_or_create_by(name: "2K Games")
Brand.find_or_create_by(name: "Skillz (company)")
Brand.find_or_create_by(name: "Square (video game company)")
Brand.find_or_create_by(name: "Wargaming (company)")
Brand.find_or_create_by(name: "BioWare")
Brand.find_or_create_by(name: "Sabai Ecoverse")
Brand.find_or_create_by(name: "Paradox Interactive")
Brand.find_or_create_by(name: "Activision Blizzard")
Brand.find_or_create_by(name: "Bandai")
Brand.find_or_create_by(name: "Cd Projekt Red")
Brand.find_or_create_by(name: "Unity Technologies")
Brand.find_or_create_by(name: "Warner Bros.")
Brand.find_or_create_by(name: "RedSpotGames")
Brand.find_or_create_by(name: "CodeCombat")
Brand.find_or_create_by(name: "Valve Corporation")
Brand.find_or_create_by(name: "Maxis")
Brand.find_or_create_by(name: "Call of Duty")
Brand.find_or_create_by(name: "Subway Princess Runner")
Brand.find_or_create_by(name: "7 Days to Die")
Brand.find_or_create_by(name: "Climax Studios")
Brand.find_or_create_by(name: "Coffee Stain Studios")
Brand.find_or_create_by(name: "Glu Mobile")
Brand.find_or_create_by(name: "InXile Entertainment")
Brand.find_or_create_by(name: "Riot Games")
Brand.find_or_create_by(name: "Lionhead Studios")
Brand.find_or_create_by(name: "DICE (company)")
Brand.find_or_create_by(name: "The 3DO Company")
Brand.find_or_create_by(name: "Saber Interactive")
Brand.find_or_create_by(name: "Crytek")
Brand.find_or_create_by(name: "Bandai Namco Entertainment")
Brand.find_or_create_by(name: "Interplay Entertainment")
Brand.find_or_create_by(name: "Rayman Legends")
Brand.find_or_create_by(name: "NEC")
Brand.find_or_create_by(name: "NCsoft")
Brand.find_or_create_by(name: "Kalypso Media")
Brand.find_or_create_by(name: "Capcom")
Brand.find_or_create_by(name: "Supercell (video game company)")
Brand.find_or_create_by(name: "Criterion Games")
Brand.find_or_create_by(name: "Level-5 (company)")
Brand.find_or_create_by(name: "Dentsu")
Brand.find_or_create_by(name: "Naughty Dog")
Brand.find_or_create_by(name: "Acheron Design")
Brand.find_or_create_by(name: "THQ")
Brand.find_or_create_by(name: "Konami")
Brand.find_or_create_by(name: "Quantic Dream")
Brand.find_or_create_by(name: "Natsume (company)")
Brand.find_or_create_by(name: "BLUE BOX Game Studios")
Brand.find_or_create_by(name: "Hearthstone (video game)")
Brand.find_or_create_by(name: "Gameloft")
Brand.find_or_create_by(name: "CD Projekt S.A.")
Brand.find_or_create_by(name: "New World Interactive")
Brand.find_or_create_by(name: "Blizzard Entertainment")
Brand.find_or_create_by(name: "Sony Interactive Entertainment")
Brand.find_or_create_by(name: "Studio Ghibli")
Brand.find_or_create_by(name: "Sega")
Brand.find_or_create_by(name: "GSC Game World")
Brand.find_or_create_by(name: "NaturalMotion")
Brand.find_or_create_by(name: "Hero Concept")
Brand.find_or_create_by(name: "Cygames")
Brand.find_or_create_by(name: "Arkane Studios")
Brand.find_or_create_by(name: "Tencent Games")
Brand.find_or_create_by(name: "Infocom")
Brand.find_or_create_by(name: "Harmonix")
Brand.find_or_create_by(name: "Bohemia Interactive")
Brand.find_or_create_by(name: "Monolith Soft")
Brand.find_or_create_by(name: "Penguin Karts")
Brand.find_or_create_by(name: "Bytro Labs")
Brand.find_or_create_by(name: "CCP Games")
Brand.find_or_create_by(name: "Cyanide (company)")
Brand.find_or_create_by(name: "Cryo Interactive")
Brand.find_or_create_by(name: "Moon Nation Game")
Brand.find_or_create_by(name: "Intelligent Systems")
Brand.find_or_create_by(name: "Game Freak")
Brand.find_or_create_by(name: "Capcom Vancouver")
Brand.find_or_create_by(name: "2K Czech")
Brand.find_or_create_by(name: "Snake game")
Brand.find_or_create_by(name: "Techland")
Brand.find_or_create_by(name: "Legend Entertainment")
Brand.find_or_create_by(name: "Zodiacs")
Brand.find_or_create_by(name: "Cave (company)")
Brand.find_or_create_by(name: "Ngmoco")
Brand.find_or_create_by(name: "N-Space")
Brand.find_or_create_by(name: "Battle World")
Brand.find_or_create_by(name: "Electronic Arts (Ea)")
Brand.find_or_create_by(name: "Campo Santo (company)")
Brand.find_or_create_by(name: "UserJoy Technology")
Brand.find_or_create_by(name: "PopCap Games")
Brand.find_or_create_by(name: "Garena")
Brand.find_or_create_by(name: "MachineGames")
Brand.find_or_create_by(name: "Infinity Ward")
Brand.find_or_create_by(name: "Mojang")
Brand.find_or_create_by(name: "Gaijin Entertainment")
Brand.find_or_create_by(name: "MicroProse")
Brand.find_or_create_by(name: "Nexters")
Brand.find_or_create_by(name: "Cartoon Network")
Brand.find_or_create_by(name: "Monolith Productions")
Brand.find_or_create_by(name: "Bigpoint Games")
Brand.find_or_create_by(name: "Toei Animation")
Brand.find_or_create_by(name: "Esportz Entertainment Corporation")
Brand.find_or_create_by(name: "Smule")
Brand.find_or_create_by(name: "3D Realms")
Brand.find_or_create_by(name: "Starform, Inc.")
Brand.find_or_create_by(name: "Pubg Corporation")
Brand.find_or_create_by(name: "Kojima Productions")
Brand.find_or_create_by(name: "FreshPlanet")
Brand.find_or_create_by(name: "Bugbear Entertainment")
Brand.find_or_create_by(name: "Kabam")
Brand.find_or_create_by(name: "Behaviour Interactive")
Brand.find_or_create_by(name: "King.com")
Brand.find_or_create_by(name: "Gearbox Software")
Brand.find_or_create_by(name: "IO Interactive")
Brand.find_or_create_by(name: "PlayFirst")
Brand.find_or_create_by(name: "InnoGames")
Brand.find_or_create_by(name: "HandyGames")
Brand.find_or_create_by(name: "Take-Two Interactive")
Brand.find_or_create_by(name: "Black Isle Studios")
Brand.find_or_create_by(name: "Midas Interactive Entertainment")
Brand.find_or_create_by(name: "Square Enix")
Brand.find_or_create_by(name: "EA Gothenburg")
Brand.find_or_create_by(name: "ZeniMax Media")
Brand.find_or_create_by(name: "3G Studios")
Brand.find_or_create_by(name: "Altar Games")
Brand.find_or_create_by(name: "Unreal Engine")
Brand.find_or_create_by(name: "Peak Games")
Brand.find_or_create_by(name: "Degica")
Brand.find_or_create_by(name: "Respawn Entertainment")
Brand.find_or_create_by(name: "Paradox Interactive")
Brand.find_or_create_by(name: "11 bit studios")
Brand.find_or_create_by(name: "EA Sports")
Brand.find_or_create_by(name: "Hazelight Studios")
Brand.find_or_create_by(name: "Shots Studios")
Brand.find_or_create_by(name: "DeFi Degen Land")
Brand.find_or_create_by(name: "Com2uS")
Brand.find_or_create_by(name: "4A Games")
Brand.find_or_create_by(name: "Hudson Soft")
Brand.find_or_create_by(name: "THQ Nordic")
Brand.find_or_create_by(name: "Oberon Media")
Brand.find_or_create_by(name: "SYBO Games")
Brand.find_or_create_by(name: "Illusion (company)")
Brand.find_or_create_by(name: "Edge of Reality (video game company)")
Brand.find_or_create_by(name: "Dambuster Studios")
Brand.find_or_create_by(name: "Black Forest Games")
Brand.find_or_create_by(name: "Codemasters")
Brand.find_or_create_by(name: "Rockstar North")
Brand.find_or_create_by(name: "Ensemble Studios")
Brand.find_or_create_by(name: "Mythic Entertainment")
Brand.find_or_create_by(name: "HeroCraft")
Brand.find_or_create_by(name: "Gameforge")
Brand.find_or_create_by(name: "Deathloop")
Brand.find_or_create_by(name: "Humble Bundle")
Brand.find_or_create_by(name: "Nadeo")
Brand.find_or_create_by(name: "Bandai Namco Holdings")
Brand.find_or_create_by(name: "Playfish")
Brand.find_or_create_by(name: "Jagex")
Brand.find_or_create_by(name: "Tuque Games")
Brand.find_or_create_by(name: "Atlantis Computing")
Brand.find_or_create_by(name: "Arc System Works")
Brand.find_or_create_by(name: "Luxoflux")
Brand.find_or_create_by(name: "989 Studios")
Brand.find_or_create_by(name: "Wooga")
Brand.find_or_create_by(name: "Larian Studios")
Brand.find_or_create_by(name: "Lesta Studio")
Brand.find_or_create_by(name: "Bethesda")
Brand.find_or_create_by(name: "GameDuell")
Brand.find_or_create_by(name: "Deep Silver")
Brand.find_or_create_by(name: "Yousician")
Brand.find_or_create_by(name: "Mundfish")
Brand.find_or_create_by(name: "Curve Digital Limited")
Brand.find_or_create_by(name: "Rovio Entertainment")
Brand.find_or_create_by(name: "Hands-On Mobile")
Brand.find_or_create_by(name: "Misfits Gaming")
Brand.find_or_create_by(name: "Bilibili")
Brand.find_or_create_by(name: "Palette (company)")
Brand.find_or_create_by(name: "Neowiz")
Brand.find_or_create_by(name: "Jakks Pacific")